--Users2
CREATE TABLE IF NOT EXISTS Users (
id uuid PRIMARY KEY DEFAULT uuid_generate_v4()
,name VARCHAR(255) NOT NULL
,email VARCHAR(255) NOT NULL
,age INT NOT NULL
,address VARCHAR(255) NOT NULL
,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW() 
,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW() 
);
